version: "3"
services:
  crypto-trade-db:
    image: "postgres:14.6"
    container_name: crypto-trade-db
    volumes:
      - crypto-trade_data:/var/lib/postgresql/data
    networks:
      - crypto-trade
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  crypto-trade:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-trade
    container_name: crypto-trade
    restart: always
    networks:
      - crypto-trade
    volumes:
      - ./:/app
      - ./config.yaml:/app/config.yaml
    ports:
      - 8001:8001
    depends_on:
      - crypto-trade-db
      - crypto-trade-redis
  
  crypto-trade-redis:
    image: "redis:latest"
    container_name: crypto-trade-redis
    networks:
      - crypto-trade

  crypto-trade-kafka:
    image: bitnami/kafka:latest
    container_name: crypto-trade-kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://crypto-trade-kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=crypto-trade-zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - crypto-trade
    depends_on:
      - crypto-trade-zookeeper

  crypto-trade-zookeeper:
    image: bitnami/zookeeper:latest
    container_name: crypto-trade-zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - crypto-trade 

volumes:
  crypto-trade_data:

networks:
  crypto-trade:
    name: crypto-trade
    driver: bridge