name: Releaser
on:
  release:
    types:
      - published
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd go/projects/go-base-project-structure
            git fetch --all
            git checkout ${{ github.event.release.tag_name }}

            docker compose -f docker-compose.yml stop go-base-project-structure
            docker compose -f docker-compose.yml rm -f go-base-project-structure
            docker compose -f docker-compose.yml up -d --build go-base-project-structure